services:
  mongo:
    image: mongo:8
    container_name: trading-simulator-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - trading_simulator_mongo:/data/db

volumes:
  trading_simulator_mongo:
