import { Router } from "express";
import { register, login, me, updateProfile, removeAccount } from "../controllers/authController.js";
import protect from "../middleware/authMiddleware.js";
const router = Router();
router.post("/register", register);
router.post("/login", login);
router.get("/me", protect, me);
router.put("/me", protect, updateProfile);
router.delete("/me", protect, removeAccount);
export default router;
